import { C, TEAM_COLORS } from '../config/constants';

export const styles = {
  app: { background: C.bg, minHeight: "100vh", color: C.white, fontFamily: "'Pretendard', -apple-system, BlinkMacSystemFont, sans-serif", maxWidth: 500, margin: "0 auto", paddingBottom: 80 },
  header: { background: "linear-gradient(135deg, #0891b2, #6366f1)", padding: "16px", textAlign: "center", position: "sticky", top: 0, zIndex: 100 },
  title: { fontSize: 20, fontWeight: 800, color: C.white },
  subtitle: { fontSize: 12, color: "rgba(255,255,255,0.7)", marginTop: 2 },
  section: { padding: 16 },
  sectionTitle: { fontSize: 15, fontWeight: 700, marginBottom: 10, color: C.accent, display: "flex", alignItems: "center", gap: 6 },
  card: { background: C.card, borderRadius: 12, padding: 14, marginBottom: 10 },
  btn: (bg, tc = "#fff") => ({ background: bg, color: tc, border: "none", borderRadius: 8, padding: "10px 16px", fontSize: 14, fontWeight: 600, cursor: "pointer" }),
  btnFull: (bg, tc = "#fff") => ({ background: bg, color: tc, border: "none", borderRadius: 8, padding: "10px 16px", fontSize: 14, fontWeight: 600, cursor: "pointer", width: "100%", display: "block" }),
  btnSm: (bg, tc = "#fff") => ({ background: bg, color: tc, border: "none", borderRadius: 6, padding: "6px 12px", fontSize: 12, fontWeight: 600, cursor: "pointer" }),
  chip: (active) => ({ display: "inline-flex", alignItems: "center", gap: 4, padding: "8px 14px", borderRadius: 20, fontSize: 13, fontWeight: 600, margin: 3, cursor: "pointer", background: active ? C.accent : C.cardLight, color: active ? C.bg : C.gray, border: `2px solid ${active ? C.accent : "transparent"}`, transition: "all 0.15s" }),
  row: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },
  input: { background: C.cardLight, border: `1px solid ${C.grayDark}`, borderRadius: 8, padding: "8px 12px", color: C.white, fontSize: 14, outline: "none", width: "100%" },
  scoreboard: { display: "flex", alignItems: "center", justifyContent: "center", gap: 16, padding: "12px 0", fontSize: 36, fontWeight: 900, color: C.white },
  th: { padding: "8px 4px", textAlign: "center", color: C.gray, borderBottom: `1px solid ${C.grayDarker}`, fontWeight: 600, fontSize: 11 },
  td: (hl = false) => ({ padding: "8px 4px", textAlign: "center", borderBottom: `1px solid ${C.grayDarker}`, fontWeight: hl ? 700 : 400, color: hl ? C.accent : C.white, fontSize: 12 }),
  tabRow: { display: "flex", gap: 0, marginBottom: 12 },
  tab: (active) => ({ flex: 1, padding: "10px", textAlign: "center", background: active ? C.accent : C.card, color: active ? C.bg : C.gray, fontWeight: 700, fontSize: 14, border: "none", cursor: "pointer", borderRadius: 0 }),
  bottomBar: { position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 500, background: C.card, borderTop: `1px solid ${C.grayDarker}`, padding: "10px 16px", display: "flex", gap: 8, zIndex: 100 },
  phaseIndicator: { display: "flex", justifyContent: "center", gap: 8, padding: "8px 0", background: "rgba(0,0,0,0.2)" },
  dot: (active) => ({ width: 8, height: 8, borderRadius: "50%", background: active ? C.accent : C.grayDark }),
  eventLog: { display: "flex", alignItems: "center", padding: "6px 10px", borderRadius: 8, background: C.cardLight, marginBottom: 4, fontSize: 12, gap: 6, color: C.white },
  teamCard: (ci) => ({ background: C.card, borderRadius: 12, padding: 12, marginBottom: 10, borderLeft: `4px solid ${TEAM_COLORS[ci]?.bg || C.accent}` }),
  playerInTeam: (color) => ({ display: "inline-flex", alignItems: "center", padding: "6px 10px", borderRadius: 8, fontSize: 12, fontWeight: 600, margin: 2, background: `${color?.bg || C.cardLight}22`, color: color?.text === "#fff" ? C.white : color?.text || C.white, border: `1px solid ${color?.bg || C.grayDark}44` }),
  matchBtn: (color) => ({ display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "12px 16px", borderRadius: 10, fontSize: 14, fontWeight: 700, margin: 3, cursor: "pointer", background: color?.bg || C.cardLight, color: color?.text || C.white, minWidth: 60, border: "none" }),
};
