// src/styles/theme.js — Apple HIG.
// makeStyles(C) signature and keys preserved. Values shift to Apple iOS tones.

import { TEAM_COLORS } from '../config/constants';

export function makeStyles(C) {
  return {
    app: {
      background: C.bg,
      minHeight: "100vh",
      color: C.white,
      fontFamily: "var(--app-font-sans)",
      fontFeatureSettings: '"kern" 1',
      fontWeight: 400,
      letterSpacing: "-0.014em",
      maxWidth: 500,
      margin: "0 auto",
      paddingBottom: 80,
    },
    header: {
      background: C.bg,
      borderBottom: `0.5px solid ${C.borderColor}`,
      padding: "14px 16px",
      textAlign: "center",
      position: "sticky",
      top: 0,
      zIndex: 100,
    },
    title: {
      fontSize: 17,
      fontWeight: 600,
      color: C.white,
      letterSpacing: "-0.022em",
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      justifyContent: "center",
    },
    subtitle: {
      fontFamily: "inherit",
      fontSize: 13,
      letterSpacing: 0,
      textTransform: "none",
      color: C.gray,
      marginTop: 2,
    },
    section: { padding: 16 },
    sectionTitle: {
      fontFamily: "inherit",
      fontSize: 13,
      letterSpacing: 0,
      textTransform: "none",
      marginBottom: 8,
      color: C.gray,
      display: "flex",
      alignItems: "center",
      gap: 6,
      paddingLeft: 4,
    },
    card: {
      background: C.card,
      border: `1px solid ${C.borderColor}`,
      borderRadius: 14,
      padding: 14,
      marginBottom: 10,
    },

    btn: (bg, tc) => ({
      background: bg || C.accent,
      color: tc || "#fff",
      border: "none",
      borderRadius: 10,
      padding: "11px 16px",
      minHeight: 40,
      fontSize: 15,
      fontWeight: 500,
      letterSpacing: "-0.01em",
      cursor: "pointer",
      transition: "opacity .15s, transform .05s",
    }),
    btnFull: (bg, tc) => ({
      background: bg || C.accent,
      color: tc || "#fff",
      border: "none",
      borderRadius: 12,
      padding: "13px 18px",
      minHeight: 50,
      fontSize: 16,
      fontWeight: 600,
      letterSpacing: "-0.01em",
      cursor: "pointer",
      width: "100%",
      display: "block",
    }),
    btnSm: (bg, tc) => ({
      background: bg || C.cardLight,
      color: tc || C.white,
      border: "none",
      borderRadius: 8,
      padding: "6px 12px",
      minHeight: 28,
      fontSize: 13,
      fontWeight: 500,
      cursor: "pointer",
    }),

    chip: (active) => ({
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
      padding: "6px 12px",
      borderRadius: 999,
      fontSize: 13,
      fontWeight: 500,
      margin: 3,
      cursor: "pointer",
      background: active ? C.accent : C.cardLight,
      color: active ? "#fff" : C.white,
      border: "none",
      transition: "all 0.12s",
    }),

    row: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" },

    input: {
      background: C.cardLight,
      border: `1px solid transparent`,
      borderRadius: 10,
      padding: "11px 12px",
      color: C.white,
      fontSize: 16,
      fontWeight: 400,
      letterSpacing: "-0.01em",
      outline: "none",
      width: "100%",
      fontFamily: "inherit",
      transition: "border-color .12s, background .12s",
    },

    scoreboard: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 20,
      padding: "8px 0",
      fontSize: 56,
      fontWeight: 600,
      letterSpacing: "-0.03em",
      lineHeight: 1,
      fontVariantNumeric: "tabular-nums",
      color: C.white,
    },

    th: {
      padding: "8px 4px",
      textAlign: "center",
      color: C.gray,
      borderBottom: `1px solid ${C.grayDarker}`,
      fontFamily: "inherit",
      fontWeight: 500,
      fontSize: 12,
      letterSpacing: 0,
      textTransform: "none",
    },
    td: (hl = false) => ({
      padding: "10px 4px",
      textAlign: "center",
      borderBottom: `0.5px solid ${C.grayDarker}`,
      fontWeight: hl ? 600 : 400,
      color: hl ? C.white : C.gray,
      fontSize: 14,
      fontVariantNumeric: "tabular-nums",
    }),

    tabRow: {
      display: "flex",
      gap: 6,
      marginBottom: 12,
      padding: "4px",
      background: C.cardLight,
      borderRadius: 10,
      overflowX: "auto",
      scrollbarWidth: "none",
    },
    tab: (active) => ({
      flex: "0 0 auto",
      padding: "6px 14px",
      textAlign: "center",
      background: active ? C.card : "transparent",
      color: active ? C.white : C.gray,
      fontWeight: 500,
      fontSize: 13,
      letterSpacing: 0,
      border: "none",
      borderRadius: 7,
      boxShadow: active ? "0 1px 2px rgba(0,0,0,0.08)" : "none",
      cursor: "pointer",
    }),

    bottomBar: {
      position: "fixed",
      bottom: 0,
      left: "50%",
      transform: "translateX(-50%)",
      width: "100%",
      maxWidth: 500,
      background: C.card,
      borderTop: `0.5px solid ${C.borderColor}`,
      padding: "10px 16px 20px",
      display: "flex",
      gap: 8,
      zIndex: 100,
      paddingBottom: "max(20px, env(safe-area-inset-bottom))",
    },

    phaseIndicator: {
      display: "flex",
      justifyContent: "center",
      gap: 6,
      padding: "8px 0",
      background: "transparent",
    },
    dot: (active) => ({
      width: active ? 20 : 6,
      height: 6,
      borderRadius: 3,
      background: active ? C.accent : C.grayDarker,
      transition: "all .2s",
    }),

    eventLog: {
      display: "flex",
      alignItems: "center",
      padding: "10px 12px",
      borderRadius: 10,
      background: C.cardLight,
      border: "none",
      marginBottom: 6,
      fontSize: 14,
      gap: 8,
      color: C.white,
    },

    teamCard: (ci) => ({
      background: C.card,
      borderRadius: 14,
      padding: 14,
      marginBottom: 10,
      border: `1px solid ${C.borderColor}`,
      boxShadow: "none",
    }),

    playerInTeam: (color) => ({
      display: "inline-flex",
      alignItems: "center",
      gap: 6,
      padding: "6px 10px",
      borderRadius: 999,
      fontSize: 13,
      fontWeight: 500,
      margin: 2,
      background: C.cardLight,
      color: C.white,
      border: "none",
      "--dot-color": color?.bg || "transparent",
    }),

    matchBtn: (color) => ({
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      padding: "10px 14px",
      borderRadius: 10,
      fontSize: 14,
      fontWeight: 500,
      margin: 3,
      cursor: "pointer",
      background: C.cardLight,
      color: C.white,
      minWidth: 60,
      border: "none",
    }),
  };
}
